monolog:
    handlers:
        # console:
        #     type: console
        #     verbosity_levels:
        #         VERBOSITY_NORMAL: DEBUG
        #     channels: import
        #     formatter: monolog.import.formatter
        graby:
            type: service
            id: graby.log_handler
            level: debug
            channels: ['graby']
