swarrot:
    provider: amqp_lib
    connections:
        rabbitmq:
            url: "amqp://%env(RABBITMQ_LOGIN)%:%env(RABBITMQ_PASSWORD)%@%env(RABBITMQ_HOST)%:%env(int:RABBITMQ_PORT)%/"
    consumers:
        f43.fetch_items:
            processor: App\Consumer\FetchItems
            extras:
                poll_interval: 500000
            middleware_stack:
                - configurator: swarrot.processor.max_messages
                  extras:
                      max_messages: 20
                - configurator: swarrot.processor.doctrine_connection
                - configurator: swarrot.processor.retry
                - configurator: swarrot.processor.exception_catcher
                - configurator: swarrot.processor.ack
    messages_types:
        f43.fetch_items.publisher:
            connection: rabbitmq
            exchange: f43.fetch_items
