dist: xenial
os: linux
language: php

# avoid double Travis build when the PR is created on upstream
if: |
    type = pull_request OR \
    branch = master

addons:
    apt:
        packages:
            - rabbitmq-server
            - pkg-config
            - librabbitmq-dev
            - librabbitmq4

services:
    - mysql

php:
    - 7.4
    - nightly

# run build against nightly but allow them to fail
jobs:
    fast_finish: true
    include:
        - php: 7.2
          env: COVERAGE=run
        - php: 7.3
          env: CS_FIXER=run
    allow_failures:
        - php: nightly

# cache vendor dirs
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
    - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    # install amqp
    - pear config-set preferred_state beta
    - pecl channel-update pecl.php.net
    - printf "\n" | pecl install amqp

install:
    - composer install --no-interaction --optimize-autoloader --no-progress --prefer-dist --no-suggest
    - php bin/simple-phpunit install

before_script:
    # using dev env because tests queues are "in memory"
    - php bin/console messenger:setup-transports --env=dev
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - if [ $COVERAGE = run ]; then PHPUNIT_FLAGS="--coverage-clover build/logs/clover.xml"; fi;

script:
    - make prepare
    - mkdir -p build/logs
    - php bin/simple-phpunit -v $PHPUNIT_FLAGS
    - if [ "$CS_FIXER" = "run" ]; then php bin/php-cs-fixer fix --verbose --dry-run ; fi;
    - if [ "$CS_FIXER" = "run" ]; then php bin/phpstan analyse --no-progress ; fi;

after_success:
    - |
        if [ $COVERAGE = run ]; then
            wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.4.2/php-coveralls.phar
            chmod +x php-coveralls.phar

            php php-coveralls.phar -v -x build/logs/clover.xml
        fi
